### ISSUE TITLE
Using polynomial-regression on browser

### ISSUE THREAD

**Issue by doleron** [danielherrerohernando/polynomial-regression#10]
Hi, thank you for the library.

I'd like to know if is that possible to use this library on browser and how.

So, far I tried to include:
````html
<script src="https://cdn.jsdelivr.net/npm/polynomial-regression@1.1.0/src/index.min.js">
</script>
````
But I think that this jsdelivr version does not work. Any tips?

Best,
Luiz

**Comment by danielherrerohernando** [comment]
Hi @doleron, you could easily use the library in a frontend app by installing and requiring it at any file, however, that's not possible at the moment because it depends on the "fs" module (only available in Node) for some operations (which are not part of the core functionality btw).

So... I'm afraid this requires a little refactor to avoid the error of "fs" module not found in the browser when loading the library.

**Comment by doleron** [comment]
Ok, thanks for the feedback @danielherrerohernando 
Feel free to close the issue.
Best,
Luiz

**Comment by runk** [comment]
Hey @danielherrerohernando 👋 

I stuck at the same issue with `fs`. Would you accept a PR if I were to remove a dependency on it? I'm thinking along the line of exporting/importing coefficients as js object instead of saving/loading them to file. This should make it possible to persist parameters anywhere (like a conventional db or whatever), as well as removes a dependency.

**Comment by runk** [comment]
I figured I may just do that: https://github.com/danielherrerohernando/polynomial-regression/pull/12

**Comment by danielherrerohernando** [comment]
Closed after merging  https://github.com/danielherrerohernando/polynomial-regression/pull/12
